= Desafio Tecnico

== Sobre o App:

Um pequeno time de apenas três desenvolvedores apaixonados por tecnologia criaram o web app Organizeasly(C), um aplicativo revolucionário voltado para facilitar a organização de eventos.

A princípio era somente um hobby para conectar fornecedores e prestadores de serviço a quem queria realizar algum evento, dando match inclusive com a previsão do tempo e evitando concorrência do público com outros eventos.

Com uma interface intuitiva, 100% web e um algoritmo de recomendação de locais e serviços de alta precisão usando APIs de terceiros, o Organizeasly(C) começou a ganhar popularidade e atraiu o interesse de uma grande empresa que organiza eventos, conferências e feiras.

O Organizeasly(C) recebeu um aporte financeiro, e com isto a necessidade de reestruturá-lo totalmente para comportar o crescimento exponencial.

=== Situação atual:

O aplicativo possui 3 componentes:

- _Front-end web_: +Jquery, JavaScript, html, css, Ruby on Rails (Opal lib)+;
- _Back-end_: +Ruby on Rails (e alguns crons em python e bash!)+;
- _Database_: +MySQL+

[source,mermaid]
....
flowchart TB
subgraph CentOS6
front-->back
back --> database
end
....

`Muito *simples* né?`


Tudo roda dentro de apenas um único servidor, sendo tratado com muito cuidado, como um verdadeiro Pet, dentro de num provedor de VPS não muito confiável.

Deploy é via SSH ou FTP direto no servidor Linux, um CentOS 6.

O código está no github.

E já está dando um bom lucro!

Os investidores querem que num futuro seja migrado para frameworks mais famosos, como vue.js, node.js e possuem um grande roadmap de melhorias, inovações e novas contratações de desenvolvedores.... 

*Mas antes, precisamos organizar tudo!*

=== Desafio:

Você como DevOps, SRE, Sysadmin (esqueci outro nome? rsrss), deverá propor uma nova estrutura para o app dentro da AWS!



* [ ] crie uma branch deste repositório;

* [ ]  no diretório “proposta” crie uma pasta com seu nome e faça o commit da sua atividade nela;

* [ ] Desenhe no http://excalidraw.io/[excalidraw^], http://draw.io/[drawio^] ou https://www.cloudcraft.co/[Cloudcraft^] qual a sua proposta de reestruturação do app;

* [ ] Crie a infraestrutura do aplicativo utilizando terraform; (opcional para candidatos juniores)

* [ ] quando finalizar, crie uma Pull Request para a branch Main.




.Tenha em mente:
[IMPORTANT]
===============================
- framework well-architected
- alta disponibilidade e resiliência
- segurança
===============================



==== Opcional:
* Após propor a infraestrutura do aplicativo, sinta-se livre para complementar no desenho (ou caso queira, no terraform) com os seguintes itens:

    - processo de CI/CD;
    - estrutura de backups;
    - monitoramento;
    - recuperação de desastre;



Este desafio não possui resposta certa, ele é aplicado a candidatos para vaga de Junior, Pleno e Sênior.

Este desafio não é imperativo nem eliminatório durante o processo seletivo, mas irá direcionar o bate-papo na entrevista técnica.



organize easily = Organizeasly(C) (Organize facilmente)... Sim, terão que mudar o nome tbm ;-)